replicaCount: 1

image:
  repository: 371726673826.dkr.ecr.us-east-1.amazonaws.com/raffle-app
  tag: "0.1.14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: raffle.yourdomain.com

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"