apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: raffle-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: raffle-ui
  template:
    metadata:
      labels:
        app: raffle-ui
    spec:
      containers:
      - name: raffle-ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: HOSTNAME
          value: "0.0.0.0" # <-- Next.js barcha tarmoq interfeyslarida eshitishi uchun SHART
        - name: PORT
          value: "3000"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
          name: http
        
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5