apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-argocd-app-manager
  namespace: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-argocd-app-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: runner-argocd-app-manager
  apiGroup: rbac.authorization.k8s.io