export const RAFFLE_ADDRESS = "0xc2cb8835769662d48E31A4272Bfde1A2530DD9b4" as const

export const RAFFLE_ABI = [
  { type:"function", name:"enterRaffle", inputs:[], outputs:[], stateMutability:"payable" },
  { type:"function", name:"claimWinnings", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"claimRefund", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"pause", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"unpause", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"cancelRaffle", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"emergencyWithdraw", inputs:[], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"setEntranceFee", inputs:[{ name:"newFee", type:"uint256", internalType:"uint256" }], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"setProtocolFee", inputs:[{ name:"newBps", type:"uint256", internalType:"uint256" }], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"setTreasury", inputs:[{ name:"newTreasury", type:"address", internalType:"address" }], outputs:[], stateMutability:"nonpayable" },
  { type:"function", name:"owner", inputs:[], outputs:[{ name:"", type:"address", internalType:"address" }], stateMutability:"view" },
  { type:"function", name:"getRaffleState", inputs:[], outputs:[{ name:"", type:"uint8", internalType:"enum Raffle.RaffleState" }], stateMutability:"view" },
  { type:"function", name:"getEntranceFee", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getCurrentRoundPot", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getNumberOfPlayers", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getLastTimeStamp", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getInterval", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getRecentWinner", inputs:[], outputs:[{ name:"", type:"address", internalType:"address" }], stateMutability:"view" },
  { type:"function", name:"getWinnerHistory", inputs:[], outputs:[{ name:"", type:"address[]", internalType:"address[]" }], stateMutability:"view" },
  { type:"function", name:"getCurrentRoundId", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getPendingClaims", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getProtocolFeeBps", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getTreasury", inputs:[], outputs:[{ name:"", type:"address", internalType:"address" }], stateMutability:"view" },
  { type:"function", name:"getTotalRoundsPlayed", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"MAX_PLAYERS", inputs:[], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"isPaused", inputs:[], outputs:[{ name:"", type:"bool", internalType:"bool" }], stateMutability:"view" },
  { type:"function", name:"hasEntered", inputs:[{ name:"a", type:"address", internalType:"address" }], outputs:[{ name:"", type:"bool", internalType:"bool" }], stateMutability:"view" },
  { type:"function", name:"getWinnings", inputs:[{ name:"a", type:"address", internalType:"address" }], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getRefund", inputs:[{ name:"a", type:"address", internalType:"address" }], outputs:[{ name:"", type:"uint256", internalType:"uint256" }], stateMutability:"view" },
  { type:"function", name:"getRoundResult", inputs:[{ name:"roundId", type:"uint256", internalType:"uint256" }], outputs:[{ name:"", type:"tuple", internalType:"struct Raffle.RoundResult", components:[{ name:"winner", type:"address", internalType:"address" },{ name:"prize", type:"uint256", internalType:"uint256" },{ name:"timestamp", type:"uint256", internalType:"uint256" },{ name:"playerCount", type:"uint256", internalType:"uint256" },{ name:"roundId", type:"uint256", internalType:"uint256" },{ name:"cancelled", type:"bool", internalType:"bool" }] }], stateMutability:"view" },
  { type:"event", name:"WinnerPicked", inputs:[{ name:"winner", type:"address", indexed:true, internalType:"address" },{ name:"prize", type:"uint256", indexed:false, internalType:"uint256" },{ name:"timestamp", type:"uint256", indexed:false, internalType:"uint256" },{ name:"roundId", type:"uint256", indexed:true, internalType:"uint256" }], anonymous:false },
  { type:"event", name:"RaffleEnter", inputs:[{ name:"player", type:"address", indexed:true, internalType:"address" },{ name:"totalPlayers", type:"uint256", indexed:false, internalType:"uint256" }], anonymous:false },
  { type:"event", name:"RaffleCancelled", inputs:[{ name:"roundId", type:"uint256", indexed:true, internalType:"uint256" },{ name:"timestamp", type:"uint256", indexed:false, internalType:"uint256" }], anonymous:false },
  { type:"error", name:"Raffle__AlreadyEntered", inputs:[] },
  { type:"error", name:"Raffle__RaffleNotOpen", inputs:[] },
  { type:"error", name:"Raffle__SendMoreToEnterRaffle", inputs:[] },
  { type:"error", name:"Raffle__MustBePaused", inputs:[] },
  { type:"error", name:"Raffle__NothingToClaim", inputs:[] },
  { type:"error", name:"Raffle__NothingToRefund", inputs:[] },
] as const
