name: Raffle UI CI/CD

on:
  push:
    branches: [main, master]
    paths:
      - 'raffle-ui/**'

# Repository'ga yangilangan package.json va values.yaml fayllarini push qilish uchun huquq beramiz
permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (Version bump uchun)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1. Version'ni +1 ga oshirish va values.yaml faylini yangilash
      - name: Bump Version & Update Helm values.yaml
        run: |
          # raffle-ui papkasiga o'tib, patch versionni oshiramiz (0.1.0 -> 0.1.1)
          cd raffle-ui
          NEW_VER=$(npm version patch --no-git-tag-version)
          CLEAN_VER=${NEW_VER#v} # 'v' harfini olib tashlaymiz -> "0.1.1"
          cd ..

          echo "NEW_VERSION=$CLEAN_VER" >> $GITHUB_ENV
          echo "Yangi versiya: $CLEAN_VER"

          # infra/helmfiles/values.yaml faylidagi 'tag: "..."' qismini yangilaymiz
          sed -i "s/tag: .*/tag: \"$CLEAN_VER\"/" infra/helmfiles/values.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Docker Image'ni Build va Push qilish (Secret build-args bilan)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./raffle-ui
          file: ./raffle-ui/Dockerfile
          push: true
          tags: |
            golibjon/my-repo:${{ env.NEW_VERSION }}
            golibjon/my-repo:latest
          build-args: |
            NEXT_PUBLIC_SEPOLIA_RPC_URL=${{ secrets.NEXT_PUBLIC_SEPOLIA_RPC_URL }}
            NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 3. Yangilangan package.json va values.yaml fayllarini Git'ga push qilish (ArgoCD uchun)
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add raffle-ui/package.json infra/helmfiles/values.yaml
          git commit -m "chore(release): bump version to ${{ env.NEW_VERSION }} [skip ci]"
          git push